version: "3.8"
services:
  app:
    build: .
    ports:
      - 4000:4000
    environment:
      HOST: 0.0.0.0
      PORT: 4000
  dev:
    extends: "app"
    build:
      context: .
      target: "build"
    command: ["npm", "run", "dev"]
    volumes:
      - ./app:/app
      - /app/node_modules
  test:
    extends: "app"
    build:
        context: .
        target: "build"
    command: ["npm", "test"]
    volumes:
      - ./app:/app
      - /app/node_modules
