on:
  push:
    branches:
      - main
name: Deploy to Heroku
jobs:
  test:
    name: Run tests on Docker image
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: docker-compose build
    - name: test
      run: docker-compose run ci
  release:
    name: Build and push the image
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@master
    - name: login
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:login
    - name: push
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:push -a typed-movies web
    - name: release
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:release -a typed-movies web
